#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LocalNotifications.Resource", IsApplication=true)]

namespace LocalNotifications
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.99")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int navigation_drawer_items_array = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int colorAccent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorPrimary = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorPrimaryDark = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int ic_launcher_background = 2130837507;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int fab_margin = 2130903040;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int back = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int btn_radio_off_dark = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int btn_radio_on_dark = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int ic_close = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ic_notification_alert = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int ic_restart = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int ic_stat_button_click = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int rounded_background = 2130968583;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int btnEvery15Min = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int btnEvery30Min = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int btnEvery5Min = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int btnEveryHour = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int btnNetSelect = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int btnNoRepeat = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int buttonGet = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int buttonNetScan = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int buttonSelectNetworks = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int buttonSubmitApi = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int buttonSubmitApiKey = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int buttonSubmitKeyVal = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int contentLayout = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int content_frame = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int deleteButton = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int displaynameInput = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int displaynameLayout = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int drawer_layout = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int gridDebug = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int gridSetup = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int inputTextApi = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int inputTextApiKey = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int inputTextApiKeyHeader = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int inputTextKey = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int inputTextValue = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int listView = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int listviewNetworks = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int nav_drawer = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int notif_messageInput = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int notif_messageLayout = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int notif_titleInput = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int notif_titleLayout = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int repeatButton = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int subtitleLabel = 2131034145;
			
			// aapt resource value: 0x7F050023
			public const int textviewLog = 2131034147;
			
			// aapt resource value: 0x7F050022
			public const int textViewName = 2131034146;
			
			// aapt resource value: 0x7F050024
			public const int textviewNullNet = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int titleTextView = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int toolbar = 2131034150;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int content_debug = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int content_main = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int content_setup = 2131099650;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F070000
			public const int list_view_drawer = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int list_view_networks = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int list_view_responses = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int popup_menu_networks = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int popup_menu_repeat = 2131165188;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F080000
			public const int ic_launcher = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int ic_launcher_foreground = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int ic_launcher_round = 2131230722;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int action_settings = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int channel_description = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int channel_name = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int navigation_drawer_close = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int navigation_drawer_open = 2131296261;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int AppTheme = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int AppTheme_AppBarOverlay = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int AppTheme_NoActionBar = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int AppTheme_PopupOverlay = 2131361795;
			
			// aapt resource value: 0x7F0A0006
			public const int control_checkable_material = 2131361798;
			
			// aapt resource value: 0x7F0A0004
			public const int Widget_App_Button_IconLeft = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int Widget_App_Button_OutlinedButton_IconOnly = 2131361797;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0B0000
			public const int network_security_config = 2131427328;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
