
name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:    
    - uses: actions/checkout@v3
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=12.0 --android=13.0

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: nuget restore 'LocalNotifications.sln'

    - name: Build
      run: msbuild 'LocalNotifications.csproj' /t:PackageForAndroid /p:Configuration=Debug
