name: Build Xamarin Android App

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the build

jobs:
  build:
    runs-on: windows-latest  # You can use the latest version of Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1 # This sets up the MSBuild environment on the runner
    
    - name: Install JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Set the desired JDK version
        distribution: 'adopt'  # Use 'adopt' distribution for JDK 11

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: '30'  # Replace with the desired SDK platform version
        ndk-version: '21.4.7075529'  # Replace with the desired NDK version
        java-version: '11'  # Should match the version you installed above
        
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5  # This sets up NuGet for package restoration

    - name: Restore NuGet packages
      run: nuget restore LocalNotifications.sln

    - name: Set up Xamarin Android environment
      run: |
        echo "MSBUILD_PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=${{ env.ANDROID_HOME }}" >> $GITHUB_ENV
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}

    - name: Build Xamarin Android project
      run: msbuild /p:Configuration=Release /t:Rebuild /p:Platform="Any CPU" LocalNotifications.sln 

    - name: Extract App Version
      run: |
        version=$(grep -oP '(?<=AssemblyVersion\(")[^"]*' Path/To/Your/AssemblyInfo.cs)
        echo "App Version: $version" >> version_output.txt
      shell: bash  # Use the bash shell for regex support

    - name: Upload Version Output
      uses: actions/upload-artifact@v2
      with:
        name: version_output
        path: version_output.txt
        
    - name: Latest Release Version
      # You may pin to the exact commit or the version.
      # uses: fangqiuming/latest-release-version@ced3ac31037d6933a46332d430919e62bb933dc0
      uses: fangqiuming/latest-release-version@v1.2.0-beta
      with:
        include_pre: true

