
name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: windowsos-latest

    steps:
    - name: Setup Xamarin
      # You may pin to the exact commit or the version.
      # uses: maxim-lobanov/setup-xamarin@00b44a3ef9e2d1953010956de2022e8d095a196c
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        # Version of Mono to select
        mono-version: 12.0
        # Version of Xamarin.Android to select
        xamarin-android-version: 13.0
    
    - uses: actions/checkout@v3
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=13.0 --android=13.0

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore 'LocalNotifications.sln'

    - name: Build
      run: msbuild 'LocalNotifications.csproj' /t:PackageForAndroid /p:Configuration=Debug
