name: Build Xamarin Android App

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the build

jobs:
  build:
    runs-on: windows-latest  # You can use the latest version of Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0  # This sets up the MSBuild environment on the runner

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5  # This sets up NuGet for package restoration

    - name: Restore NuGet packages
      run: nuget restore YourSolutionName.sln  # Replace "YourSolutionName.sln" with your actual solution file

    - name: Build Xamarin Android project
      run: msbuild /p:Configuration=Release /t:Rebuild /p:Platform="Any CPU" LocalNotifications.sln  # Replace "YourSolutionName.sln" with your actual solution file

    # Add additional steps here if you want to run tests or perform other tasks

