name: Build Xamarin Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Set up Xamarin Android environment
      run: |
        echo "MSBUILD_PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=${{ env.ANDROID_HOME }}" >> $GITHUB_ENV
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
      
    - name: Cache NuGet packages
      id: cache-nuget
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-xamarin-nuget-${{ hashFiles('**/*.sln') }}
        restore-keys: ${{ runner.os }}-xamarin-nuget-

    - name: Cache JDK
      id: cache-jdk
      uses: actions/cache@v2
      with:
        path: ${{ env.JAVA_HOME }}
        key: ${{ runner.os }}-xamarin-jdk-${{ hashFiles('**/*.sln') }}
        restore-keys: ${{ runner.os }}-xamarin-jdk-

    - name: Cache Android SDK
      id: cache-android
      uses: actions/cache@v2
      with:
        path: ${{ env.ANDROID_HOME }}
        key: ${{ runner.os }}-xamarin-android-${{ hashFiles('**/*.sln') }}
        restore-keys: ${{ runner.os }}-xamarin-android-

    - name: Install JDK 11
      if: steps.cache-jdk.outputs.cache-hit != 'true'  # Skip if cache is restored
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Android SDK
      if: steps.cache-android.outputs.cache-hit != 'true'  # Skip if cache is restored
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: '30'
        ndk-version: '21.4.7075529'
        java-version: '11'

    - name: Install NuGet packages
      if: steps.cache-nuget.outputs.cache-hit != 'true'
      run: nuget restore LocalNotifications.sln

    - name: Build Xamarin Android project
      run: msbuild /p:Configuration=Release /t:Rebuild /p:Platform="Any CPU" LocalNotifications.sln 

    - name: Save NuGet packages to cache
      if: success()  # Save the cache only if the build was successful
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-xamarin-nuget-${{ hashFiles('**/*.sln') }}

    - name: Save JDK to cache
      if: success()  # Save the cache only if the build was successful
      uses: actions/cache@v2
      with:
        path: ${{ env.JAVA_HOME }}
        key: ${{ runner.os }}-xamarin-jdk-${{ hashFiles('**/*.sln') }}

    - name: Save Android SDK to cache
      if: success()  # Save the cache only if the build was successful
      uses: actions/cache@v2
      with:
        path: ${{ env.ANDROID_HOME }}
        key: ${{ runner.os }}-xamarin-android-${{ hashFiles('**/*.sln') }}
