
name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Xamarin Android container build action
  # You may pin to the exact commit or the version.
  # uses: rheuvel89/xamarin-container-action@fbe83158557663596c88f7362d55516d394567a4
      uses: rheuvel89/xamarin-container-action@v1.14.31
      with:
        # Path to the solution file, relative to repository root
        SolutionPath: 'LocalNotifications.sln'
        # Path to the Android project file, relative to repository root
        ProjectPath: 'LocalNotifications.csproj'
        # Configuration to build with
    
    - uses: actions/checkout@v3
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=13.0 --android=13.0

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore 'LocalNotifications.sln'

    - name: Build
      run: msbuild 'LocalNotifications.csproj' /t:PackageForAndroid /p:Configuration=Debug
